[package]
name = "ada"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
unicode-normalization = "0.1.23"
unicode-data = { path = "../unicode-data" }
itertools = "0.12.1"
