#![allow(clippy::all, unused)]

mod case;
mod gc;
mod whitespace;
mod xid;

pub use case::CASE_FOLDING_SIMPLE;
pub use gc::{
    CONNECTOR_PUNCTUATION, CONTROL, DECIMAL_NUMBER, FORMAT, LETTER_NUMBER, LINE_SEPARATOR,
    LOWERCASE_LETTER, MODIFIER_LETTER, NONSPACING_MARK, OTHER_LETTER, PARAGRAPH_SEPARATOR,
    PRIVATE_USE, SPACE_SEPARATOR, SPACING_MARK, SURROGATE, TITLECASE_LETTER, UPPERCASE_LETTER,
};
pub use whitespace::WHITE_SPACE;
pub use xid::{XID_CONTINUE, XID_START};
