[package]
name = "asn1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
asn1-data = { path = "../asn1-data" }
unicode-normalization = "0.1.23"
convert_case = "0.6.0"
